-- Insert default categories
INSERT INTO categories (name, is_system, is_income, color) VALUES
-- Income categories
('Salary', TRUE, TRUE, '#10B981'),
('Freelance Income', TRUE, TRUE, '#059669'),
('Investment Income', TRUE, TRUE, '#047857'),
('Other Income', TRUE, TRUE, '#065F46'),

-- Expense categories
('Food & Dining', TRUE, FALSE, '#EF4444'),
('Restaurants', TRUE, FALSE, '#DC2626'),
('Groceries', TRUE, FALSE, '#B91C1C'),
('Transportation', TRUE, FALSE, '#F59E0B'),
('Gas & Fuel', TRUE, FALSE, '#D97706'),
('Public Transportation', TRUE, FALSE, '#B45309'),
('Shopping', TRUE, FALSE, '#8B5CF6'),
('Clothing', TRUE, FALSE, '#7C3AED'),
('Electronics', TRUE, FALSE, '#6D28D9'),
('Bills & Utilities', TRUE, FALSE, '#3B82F6'),
('Electricity', TRUE, FALSE, '#2563EB'),
('Water', TRUE, FALSE, '#1D4ED8'),
('Internet', TRUE, FALSE, '#1E40AF'),
('Phone', TRUE, FALSE, '#1E3A8A'),
('Entertainment', TRUE, FALSE, '#EC4899'),
('Movies', TRUE, FALSE, '#DB2777'),
('Games', TRUE, FALSE, '#BE185D'),
('Healthcare', TRUE, FALSE, '#06B6D4'),
('Doctor Visits', TRUE, FALSE, '#0891B2'),
('Pharmacy', TRUE, FALSE, '#0E7490'),
('Home & Garden', TRUE, FALSE, '#84CC16'),
('Home Improvement', TRUE, FALSE, '#65A30D'),
('Gardening', TRUE, FALSE, '#4D7C0F'),
('Travel', TRUE, FALSE, '#F97316'),
('Hotels', TRUE, FALSE, '#EA580C'),
('Flights', TRUE, FALSE, '#C2410C'),
('Education', TRUE, FALSE, '#22D3EE'),
('Books', TRUE, FALSE, '#06B6D4'),
('Courses', TRUE, FALSE, '#0891B2'),
('Uncategorized', TRUE, FALSE, '#6B7280');